### ISSUE TITLE
[Question] how to you create a contact item with a Home or a Mobile Phone ?

### ISSUE THREAD

**Issue by namsor** [podio/podio-java#27]
Hi, I couldn't find a Java sample with how to create a contact item with typical fields.

// works
fieldValues.add(new FieldValuesUpdate(getField(fields, "Address"), "value", contact.getPostalAddress()));
// will cause an exception to be thrown
fieldValues.add(new FieldValuesUpdate(getField(fields, "Phone"), "value", contact.getPhoneNumber()));
ItemCreate create = new ItemCreate(""+contact.getId(), fieldValues, Collections.<Integer>emptyList(), tags);
int itemId = apiFactory.getAPI(ItemAPI.class).addItem(PODIO_contact_appId, create, true);

The exception is : 
Exception in thread "main" APIException [status=Bad Request, error=invalidvalue, description=Invalid value null (null): must be one of {'workfax', 'mobile', 'work', 'private_fax', 'other', 'home', 'main'}, parameters=null]
at com.podio.ExceptionFilter.handle(ExceptionFilter.java:31)

Any help/sample/advice much appreciated.
EC

**Comment by mhrdev** [comment]
Phone field requires a "type" as well. Try something like this:

````
Map<String, String> phoneValue = new HashMap<String, String>();
phoneValue.put("type", "main");  // 'workfax', 'mobile', 'work', 'private_fax', 'other', 'home', 'main'
phoneValue.put("value",  contact.getPhoneNumber());
fieldValues.add((getField(fields, "Phone"), phoneValue)
````

**Comment by namsor** [comment]
Thanks! That worked.
