### ISSUE TITLE
Would it be possible to release 0.7.10?

### ISSUE THREAD

**Issue by anajavi** [podio/podio-java#32]
I have been running snapshot-version on production for a year now. Is it possible to do a new release?

**Comment by miguelprataleal** [comment]
I would like to have it too...

**Comment by daniel-sc** [comment]
Maybe the community fork might be if interest: https://github.com/podio-community/podio-java

**Comment by anajavi** [comment]
> Maybe the community fork might be if interest: https://github.com/podio-community/podio-java

thanks!
